# Generated by Django 2.2.2 on 2020-07-31 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_corp_action_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_download',
            name='ca_checked',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='file_download',
            name='ca_type',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='file_download',
            name='sha_file',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
