# Generated by Django 3.0.8 on 2020-08-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200801_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='securities_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISIN', models.TextField()),
                ('security_code', models.TextField()),
                ('trading_symbol', models.TextField()),
                ('security_name', models.TextField()),
                ('status', models.TextField()),
                ('security_group', models.TextField()),
                ('face_value', models.IntegerField()),
                ('industry', models.TextField()),
                ('instrument', models.TextField()),
                ('nse_listed', models.BooleanField()),
                ('bse_listed', models.BooleanField()),
                ('trading_location', models.CharField(max_length=6)),
            ],
        ),
    ]
