# Generated by Django 2.2.2 on 2020-08-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200802_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('last_time', models.DateTimeField(default=None)),
            ],
        ),
    ]
