# Generated by Django 3.0.8 on 2020-08-03 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_dashboard_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest_news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('ner_summary', models.CharField(max_length=2000)),
                ('repetition', models.IntegerField()),
            ],
        ),
    ]
