# Generated by Django 2.2.2 on 2020-08-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_company_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company_details',
        ),
    ]
