# Generated by Django 2.2.2 on 2020-07-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='corp_action_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('ca_type', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=5000)),
            ],
        ),
    ]
