# Generated by Django 2.2.2 on 2020-08-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200731_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('company_name', models.CharField(max_length=500)),
                ('error', models.IntegerField()),
                ('authors', models.CharField(max_length=1000)),
                ('publish_date', models.DateTimeField()),
                ('title', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=10000)),
                ('keywords', models.CharField(max_length=5000)),
                ('filename', models.CharField(max_length=5000)),
                ('ranks', models.FloatField()),
                ('news_checked', models.IntegerField()),
                ('ca_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('securities_ex', models.CharField(max_length=10)),
                ('company_web_link', models.CharField(max_length=10)),
                ('op_timeline', models.CharField(max_length=10)),
                ('trading_location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ca', models.TextField()),
                ('company_name', models.TextField()),
                ('ca_name', models.TextField()),
                ('security_id_type', models.TextField()),
                ('id_value', models.TextField()),
                ('ex_date', models.DateTimeField()),
                ('rec_date', models.DateTimeField()),
                ('pay_date', models.DateTimeField()),
                ('other', models.CharField(max_length=30)),
                ('exception', models.BooleanField()),
                ('remarks', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='errors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('exception', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='historic_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('ca_type', models.CharField(max_length=255)),
                ('data', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField()),
                ('to_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('keywords', models.CharField(max_length=5000)),
                ('website', models.CharField(max_length=5000)),
                ('error', models.IntegerField()),
                ('old_rank', models.FloatField()),
                ('new_rank', models.FloatField()),
                ('moved', models.IntegerField()),
                ('filename', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='securities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField()),
                ('security_type', models.CharField(max_length=100)),
                ('isin', models.CharField(max_length=50)),
                ('trade_volume', models.TextField()),
                ('listed_on_exchange', models.CharField(max_length=20)),
                ('exchange_symbol', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='webs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('web_rank', models.FloatField()),
            ],
        ),
    ]
