# Generated by Django 2.2.2 on 2020-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_articles_company_dashboard_errors_historic_data_links_pages_securities_webs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='authors',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ca_name',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='company_name',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='error',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='articles',
            name='filename',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='keywords',
            field=models.CharField(default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='news_checked',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='articles',
            name='publish_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='articles',
            name='ranks',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
