# Generated by Django 2.2.2 on 2020-08-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200801_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corp_action_data',
            name='data',
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='agenda',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='announcement_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='bonus_ratio',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='div_percent',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='div_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='ex_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='fv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='new_fv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='old_fv',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='premium',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='purpose',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='record_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='right_ratio',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='split_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='corp_action_data',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='corp_action_data',
            name='ca_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
