# Generated by Django 2.2.2 on 2020-08-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_securities_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_download',
            name='ca_extracted',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='file_download',
            name='exception_ca',
            field=models.BooleanField(default=None),
        ),
    ]
