# Generated by Django 2.2.2 on 2020-08-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200802_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='ca_list',
            name='ca_src',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
