# Generated by Django 2.2.2 on 2020-08-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_ca_list_ca_src'),
    ]

    operations = [
        migrations.RenameField(
            model_name='securities_master',
            old_name='ISIN',
            new_name='isin',
        ),
    ]
