# Generated by Django 2.2.2 on 2020-08-02 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200802_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historic_data',
            name='pay_date',
        ),
    ]
