# Generated by Django 2.2.2 on 2020-08-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_historic_data_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic_data',
            name='bc_end_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historic_data',
            name='bc_start_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historic_data',
            name='ex_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historic_data',
            name='nd_end_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historic_data',
            name='nd_start_date',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historic_data',
            name='rec_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
