# Generated by Django 3.0.8 on 2020-08-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200802_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='link',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
